Fix reload endpoint and Added docs to use this endpoint
python-microservices/pyms pull request #202
Opened 2020-10-17 19:22 UTC by avara1986

Fixes #199

Changes proposed in this PR:
- Added documentation to use the reload endpoint
- Fix error to get default path to reload

2020-10-17 20:29 UTC, alexppg requested changes

2020-10-17 20:29 UTC, alexppg commented on docs/configuration.md
> +## Reload configuration without stop your services
```suggestion
## Reload configuration without stopping your services
```

2020-10-17 20:29 UTC, alexppg commented on docs/configuration.md
> +In production environment, you could need to change configuration files without restart the microservice/pod/container.
```suggestion
In a production environment you may need to change the microservice's configuration without restarting it.
```

2020-10-17 20:29 UTC, alexppg commented on docs/configuration.md
> +This endpoint call to the method `Microservice.reload_conf()`. This method restart the services,
```suggestion
This endpoint calls the method `Microservice.reload_conf()`, which restarts the services, 
```

2020-10-17 20:29 UTC, alexppg commented on docs/configuration.md
> +cript configuration and initialize `create_app`.
Is `cript` a typo?

2020-10-17 20:29 UTC, alexppg commented on docs/configuration.md
> +It means that your libraries will be restarted, for this reason, it's important to initialize your BD,
```suggestion
This means that your libraries will be restarted, which is why it's important to initialize your BD, 
```

2020-10-17 21:58 UTC, avara1986 commented on docs/configuration.md
> +cript configuration and initialize `create_app`.
yes... :see_no_evil:

2020-10-17 23:10 UTC, alexppg requested changes

2020-10-17 23:10 UTC, alexppg commented on docs/configuration.md
> +crypt configuration and initialize `create_app`.
```suggestion
the encryption configuration and initializes `create_app`.
```

2020-10-18 00:06 UTC, alexppg approved these changes

2020-10-18 00:06 UTC, merged